### PR TITLE
Commiting the branch in Sprint1

### PR DESCRIPTION
**Pull request by Ajay8327**
Hii Team,
i was done with the POM design pattern please approve my pull request.

Regards,
Ajay Gaikwad

### CODE REVIEW

**Comment by Manali8327** [comment]
Hii Ajay,

Please re check your code and add some comment on it.
 Regards,
 Manali Manwadkar

**Comment by Ajay8327** [comment]
HIii Manali ,
 i have added all the comments please re check it,
  Regards,
  Ajay Gaikwad

**Comment by Manali8327** [comment]
Hii Ajay,

Now All Comments Looks Good you can move for code merge.
 Regards ,
  Manali Manwadkar

**Review by Manali8327 — APPROVED** [review]
Approved Looks Good

**Pull request merged**
